version: '3.7'
services:
  redis:
    container_name: redis #docker exec -it redis bash
    hostname: redis
    image: redis:6.2.6
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres